### ISSUE TITLE
Snakes receiving multiple move requests for the same game

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#205]
Possible Repro Steps (though this might be distributed race condition so good luck reproducing this) 
Create a snake
Run a game

Expected
a unique move request from the engine to the snake per move.

Actual
the same request comes in more than once within milliseconds.
Usually 2, sometimes streaks of 3.

**Comment by codeallthethingz** [comment]
> <@U3H371WP3> I’ve noticed that my snake is getting multiple concurrent move requests for the same turn of the same game sometimes. Maybe a bug?
<sub>[View in Slack](https://battlesnake.slack.com/archives/C481H117Z/p1547659380023400)</sub>

**Comment by codeallthethingz** [comment]
Probably related: https://github.com/battlesnakeio/roadmap/issues/195

**Comment by dlsteuer** [comment]
<img width="1373" alt="screen shot 2019-01-16 at 10 13 22 am" src="https://user-images.githubusercontent.com/326884/51269880-6ef79500-1978-11e9-88d0-13e2da045d8b.png">
This should help shed some light on the issue. It looks like when a game is changed from one worker to another, the last frame of the previous worker is run again on the new worker.

**Comment by ColDog** [comment]
What we think is happening:

During AddGameFrame, we try and lock the game again, but if the expiry is done, the frame won’t be written and a new worker now picks it up. Since the token expiry is set to 1 second, if the execution for that frame takes longer than 1 second the lock will expire and more workers will pick up the frame.

So effectively, the workers are flapping back and forth between processing the game frames.

Fixes to this are likely twofold:
1. Lock interval is tied to how fast the games are moving, we should maintain a background thread which watches this and refreshes at some interval less than the token expiry.
2. Expiry should also, generally, just be larger that the move timeout to avoid this issue as well. 1 second is pretty short.

Note: We can't really fully eliminate duplicated requests to the move endpoint especially during strange scenarios. This is just reducing the frequency that this can happen which is quite large now.

**Comment by codeallthethingz** [comment]
Fixed with longer lock for engine.
