### ISSUE TITLE
Snake updates before eating instead of next turn like prvious years

### ISSUE THREAD

**Issue by ntmk** [battlesnakeio/roadmap#245]
In previous years the snake when eating would move one block then on the following turn the tail would update. example from image after eating the tail would be at (0,1) then if the head moved to (0,5) the tail would stay at (0,1)

![tail](https://user-images.githubusercontent.com/25558862/52902709-6f7a8a00-31c9-11e9-95e9-185013c5daaf.png)

**Comment by bvanvugt** [comment]
We're going to adjust this to behave in the more traditional way, of having the snake tail grow on the following turn. I realize this is a pretty major mechanical change, that will impact any snake training that has happened to date. 

The dev team though thinks the current behaviour produces a pretty awkward edge case that is a) difficult to detect and b) difficult to react to. @dlsteuer has an elegant solution ready to go in battlesnakeio/engine#86 that we think makes the game easier to program against and uses the expected ruling in this situation.

Because the engine is still technically in alpha (although not for long), we're comfortable making this change now.
