### ISSUE TITLE
starter-snake-human

### ISSUE THREAD

**Issue by codeallthethingz** [battlesnakeio/roadmap#28]
A starter snake that reads input from the command line and sends those commands as responses to the next engine request.  

https://github.com/battlesnakeio/starter-snake-human

Acceptance
- uses the cursor keys for up down left right
- uses the last human input for subsequent engine calls
- uses the engines CLI interface to show you the map
- Add license: MIT
- Good readme about running this in linux/windows

**Comment by graeme-hill** [comment]
This is a good idea, especially if the game pauses until the human chooses their direction. I want to be able to do this to test how my snake handles different scenarios. It doesn't *have* to be implemented in the UI though. Instead as long as the game has a long timeout period there can be a regular snake with a normal URL that reads keyboard input to make its decision. Would be a little less seamless but it wouldn't require any changes to the actual core system (except maybe controlling the timeout).

**Comment by bvanvugt** [comment]
We've done this in previous years (dev only) where a checkbox appeared on the game creation screen to add a "local snake" which meant a hand controlled one.

The tech for this is complex, given our desired game architecture. It might be easier to implement this as a special Snake AI, instead of bake it into the game board. Imagine a website that would generate a snake URL for you and give you a UI to view the board and control the responses in real-time. This would decouple human snakes from the actual engine, and reduce complexity.

**Comment by codeallthethingz** [comment]
@dlsteuer some questions:

would it make sense to have this snake in Go so it can take advantage of the CLI stuff you're already writing?  
If so, would it also make sense to have that cli work in a separate repo or would it be trivial to include the engine code as part of this snake?

**Comment by daniel-swu** [comment]
Yeah like @bvanvugt said this is difficult given the architecture, because the engine would have to ignore the timeout for the human controlled snake, and wait for a response. This would require special configuration for it. I think a separate repo for the snake is fine, because this is really on it's own, but like I mentioned it does require engine changes to support this.

**Comment by dlsteuer** [comment]
Yeah like @bvanvugt said this is difficult given the architecture, because the engine would have to ignore the timeout for the human controlled snake, and wait for a response. This would require special configuration for it. I think a separate repo for the snake is fine, because this is really on it's own, but like I mentioned it does require engine changes to support this.

**Comment by brandonb927** [comment]
Does @ColDog Snakefest accomplish this?

**Comment by dlsteuer** [comment]
I don't think snakefest captures the idea behind a human controlled snake.

**Comment by ColDog** [comment]
No! Snakefest is coded.

**Comment by brandonb927** [comment]
I misunderstood the AC then, my apologies.

**Comment by dlsteuer** [comment]
closing this for now, as this has significant architecture issues.
